version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    volumes:
      - db:/var/lib/mysql
  server:
    depends_on:
      - mysqldb
    build: ./backend
    # restart: unless-stopped
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
    environment:
      - DB_HOST=mysqldb
      - DB_USERNAME=${MYSQLDB_USERNAME}
      - DB_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - DB_PORT=${MYSQLDB_DOCKER_PORT}
      - DB_DATABASE=${MYSQLDB_DATABASE}
      - DOCKER_PORT=${NODE_DOCKER_PORT}
      - LOCAL_PORT=${NODE_LOCAL_PORT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET=${AWS_BUCKET}
    stdin_open: true
    tty: true

volumes: 
  db: